# Generated by Django 5.2 on 2025-04-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xhs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XhsCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_id', models.CharField(max_length=35, verbose_name='创作者id')),
                ('nickname', models.CharField(max_length=20, verbose_name='昵称')),
                ('avatar', models.URLField(verbose_name='头像')),
                ('inserttime', models.DateTimeField(auto_now_add=True, verbose_name='插入时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '创作者',
                'verbose_name_plural': '创作者',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='XhsTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_id', models.CharField(max_length=35, verbose_name='创作者id')),
                ('note_ids', models.CharField(max_length=500, verbose_name='笔记数组')),
                ('inserttime', models.DateTimeField(auto_now_add=True, verbose_name='插入时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='notedetail',
            options={'managed': True, 'verbose_name': '笔记', 'verbose_name_plural': '笔记'},
        ),
    ]
