# Generated by Django 5.2 on 2025-04-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xhs', '0002_xhscreator_xhstask_alter_notedetail_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xhstask',
            name='creator_id',
            field=models.CharField(max_length=35, null=True, verbose_name='创作者id'),
        ),
        migrations.AlterField(
            model_name='xhstask',
            name='note_ids',
            field=models.CharField(max_length=500, null=True, verbose_name='笔记数组'),
        ),
    ]
